services:
  - type: web
    name: nba-pipeline
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 600
    autoDeploy: true
